### ISSUE TITLE
Struggling to run this container getting an error

### ISSUE THREAD

**Issue by privatesam** [jboillot/savapage#1]
Getting the following error:

``` 
* Starting Common Unix Printing System cupsd

   ...fail!

sh: 1: /opt/savapage/server/bin/linux-x64/app-server: not found

 * Starting Common Unix Printing System cupsd

   ...fail!

sh: 1: /opt/savapage/server/bin/linux-x64/app-server: not found

**Comment by ks-nss** [comment]
$nano docker-compose.yml 
$ docker-compose run -p 8632:8632 -p 8631:8631 --rm savapage 
WARN[0000] /home/core/docker/savapage/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 6/6
 ✔ savapage Pulled                                                                                        55.4s 
   ✔ ff65ddf9395b Pull complete                                                                            7.1s 
   ✔ dc93dd99f060 Pull complete                                                                           51.8s 
   ✔ defe7b8ee98f Pull complete                                                                           52.6s 
   ✔ 3f6cb4610743 Pull complete                                                                           53.8s 
   ✔ 4f4fb700ef54 Pull complete                                                                           53.8s 
 * Starting Common Unix Printing System cupsd                                                            [fail] 
sh: 1: /opt/savapage/server/bin/linux-x64/app-server: not found

**Comment by marki555** [comment]
That error means that the "/opt/savapage" content created during build was replaced with an empty directory from the volume during startup. Not sure why as I tested several variations of the docker-compose.yml file, but when I reverted back to the original named volumes, it was able to start cups, but nothing else.
I had to modify the startup command (either in Dockerfile or in docker-compose.yml) so that it starts also the app-server + some process which stays running forever (otherwise it would start the app-server and immediately destroy the container).
```
command: ["sh", "-c", "/etc/init.d/cups start && /opt/savapage/server/bin/linux-x64/app-server start && echo xxx && tail -f /dev/null"]
```

**Comment by jboillot** [comment]
First, sorry for the delay! It seems the volume were not initialized correctly, but I can't reproduce the bug...
Could you try the following configuration? You have to replace the two occurrences of `/volume1/docker/savapage` by the directory where you want to save your configuration and data files.

```yaml
version: '3'
services:
  savapage:
    image: jboillot/savapage:latest
    container_name: savapage
    volumes:
      - savapage_data:/opt/savapage
      - savapage_cups:/etc/cups
    ports:
      - 8632:8632
    restart: unless-stopped
    mem_limit: 2048m
    mem_reservation: 500m
    stdin_open: true
    tty: true
volumes:
  savapage_data:
    driver: local
    name: savapage_data
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/volume1/docker/savapage/data'
  savapage_cups:
    driver: local
    name: savapage_cups
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/volume1/docker/savapage/cups'
```

Don't forget to run `docker volume rm savapage_cups savapage_data` before.
